### ISSUE TITLE
Estimate current gas price

### ISSUE THREAD

**Issue by rekibnikufesin** [computablelabs/ffa-datatrust#18]
Per https://github.com/computablelabs/ffa-datatrust/pull/17#discussion_r308873542
Dynamically figure out current gas price and include in transaction.

**Comment by robrobbins** [comment]
make sure not to confuse this with something like `estimate_gas`. We know the amount of gas cuz of the vyper abi. its the `gas_price` that we don't. Like i said, I have set Skynet miners to accept `2 gwei` no matter what, but rinkedy and, especially, mainnet will not...

the frontend apps don't have this concern because we are going to shift that responsibility to the actual end user - tell them to check `ethgasstation.info` or some shit

for backend, maybe ^ has an api? or some sort of `oracle`. something to find out...

**Comment by robrobbins** [comment]
has changed a bit as we go. i put in some code to estimateGas to the FE. 

datatrust will make very few calls that need it (maybe just the register call?)

will revisit in capi
